# -*- coding: utf-8 -*-
# Generated by Django 2.2.15 on 2021-07-01 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180518_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimes_against_women',
            name='Rape_Cases_Reported',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='crimes_against_women',
            name='Victims_Above_50_Yrs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='crimes_against_women',
            name='Victims_Between_10to14_Yrs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='crimes_against_women',
            name='Victims_Between_14to18_Yrs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='crimes_against_women',
            name='Victims_Between_18to30_Yrs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='crimes_against_women',
            name='Victims_Between_30to50_Yrs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='crimes_against_women',
            name='Victims_Upto_10_Yrs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='crimes_against_women',
            name='Victims_of_Rape_Total',
            field=models.IntegerField(null=True),
        ),
    ]
