# -*- coding: utf-8 -*-
# Generated by Django 2.2.15 on 2021-07-01 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180518_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimes_against_women',
            name='Year',
            field=models.CharField(max_length=140),
        ),
    ]
