# -*- coding: utf-8 -*-
# Generated by Django 2.2.15 on 2021-07-04 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180521_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimes_against_women',
            name='Year',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='murder',
            name='Year',
            field=models.CharField(max_length=140),
        ),
    ]
